import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { useState } from "react";
import { api } from "../utils/api";

const Home: NextPage = () => {
  const [input, setInput] = useState({
    alias: "",
    topic: "",
  });

  const { mutate, data } = api.youtube.youtube.useMutation()


  return (
    <div>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <input 
        value={input.alias} 
        onChange={(e) => setInput((prev) => ({...input, alias: e.target.value}))}
        type="text"
        placeholder="Alias"
        className="border border-black"
      />

      <input 
        value={input.topic} 
        onChange={(e) => setInput((prev) => ({...input, topic: e.target.value}))}
        type="text"
        placeholder="Topic"
        className="border border-black"
      />

      <button 
        type="button"
        onClick={() => {
          mutate({ topic: input.topic, alias: '@' + input.alias })
        }}
      >Go</button>

      { data ? <p>Your Result: {data}</p> : null }
    </div>
  );
};

export default Home;
